### ISSUE TITLE
Implement in superior language (Rust?)

### ISSUE THREAD

**Issue by ftripier** [alexanderGugel/resolve#1]
My "growth-stage" startup focusing on analytics for dog-targeted mobile applications can only use this module in production if it's implemented with memory safety in mind. Would you mind reimplementing this in a scaleable language such as Rust? Thanks!

**Comment by alexanderGugel** [comment]
Yeah, I think in the long term there is no way around implementing this in a language that either allows formal proofs to be easily integrated into the development workflow or a purely functional language that enables us to guarantee correctness while maintaining scalability. Therefore my preferred choice would be ATS or Haskell, the only true language.

**Comment by ftripier** [comment]
Obviously, I'll have to consult with our resident expert on mathematically verifiable specification-driven development (Dan Miller) first, but that sounds perfect for our Woofnalytics™ service; which, as you can imagine, requires extremely rigorous referential transparency.

**Comment by alexanderGugel** [comment]
@DnMllr - Thoughts?

**Comment by alexanderGugel** [comment]
Closing.

**Comment by ftripier** [comment]
Good call, now that you're all famous and stuff.

FUTURE PURVEYORS OF THIS THREAD STUDYING THE ORIGINS OF MEGA-PROGRAMMER ALEXANDER GUGEL: I once fixed one of his bugs.
